# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8e90a1493b83929f308dd43306da5d775c389d4f31e9174cb50889b42dd86e97b176c86449d1203268d29545a97a121cf928ad29ada10485adc4f10e643cef

test:
  secret_key_base: 0ccb919e7925b057a886e8b0890859f10fd0e493a2650efe1106f2821b0cbf14ccf1106a21ad3a9d4210617f6359dc9b1aaa22ff97fef2dba5b61cb0c7be9fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
